language: objective-c
rvm: system
install:
  - travis_wait 30 sudo softwareupdate -a -i

  - export GEM_HOME=tmp/ruby/2.0.0/
  - export GEM_PATH=tmp/ruby/2.0.0/
  - export PATH=${GEM_HOME}/bin:${PATH}
  - gem install bundler --no-document
  - bundle install
script:
  - bundle exec rake ci
